project:
  type: website
  output-dir: docs

website:
  title: "Justin Rasmussen"
  navbar:
    right:
      - href: index.qmd
      - research.qmd
      - teaching.qmd
      - clinical.qmd
      - contact.qmd
      - text: "{{< ai cv size=large >}}"
        href: files/JMRasmussen_CV.pdf

format:
  html:
    theme: litera
    css: styles.css
    toc: false
    toc-location: left
    toc-title: "Sections"

editor: visual

