project:
  type: website
  output-dir: docs

website:
  title: "Justin Rasmussen"
  search: false
  favicon: network favicon.png
  navbar: 
    right:
      - text: "About"
        href: index.qmd
      - research.qmd
      - text: "Teaching"
        href: teaching.qmd
      - text: "Clinical"
        href: clinical.qmd
      - text: "Contact"
        href: contact.qmd
      - text: "{{< ai cv size=large >}}"
        href: files/JMRasmussen_CV.pdf
      - icon: mortarboard-fill
        href: https://scholar.google.com/citations?user=lfiHrAoAAAAJ&hl=en
      - icon: github
        href: https://github.com/jdrasmus1/
      - icon: bank
        href: https://scholars.duke.edu/person/justin.rasmussen

format:
  html:
    theme: litera
    css: styles.css
    toc: false
    toc-location: left
    toc-title: "Sections"

editor: visual

