---
title: "Contact"
format:
  html:
    toc: false
    page-layout: full
---

I'd love to hear from you! Send me an email at justin.rasmussen\@duke.edu. I can't provide clinical advice or referrals but I'm happy to chat about research, teaching, or other interests.

If you are a student interested in grad school in clinical psychology, I recommend checking out [Mitch’s Uncensored Advice for Applying to Graduate School in Clinical Psychology](https://mitch.web.unc.edu/wp-content/uploads/sites/4922/2017/02/MitchGradSchoolAdvice.pdf). If you have more specific questions about the process or global mental health, feel free to email me with a clear subject line and mention how you came across my profile. I'd be happy to chat about your goals and interests.

If you're interested in getting started learning R (perhaps to make [a free Quarto website](https://quarto.org/docs/websites/) like this one) check out these [Web Resources to Start Learning R](https://docs.google.com/document/d/15e8b9HFdL5ewEiWUXC_Dhw9Wx-U8Ze3-r6iFxcUTam4/edit?tab=t.0#heading=h.78m3wopkml0i) I put together.
