---
title: "Research"
---

## Interests

I am fifth-year clinical psychology PhD student working with Dr. Eve Puffer. My primary research interests center on improving access to mental health care in East Africa through professional training and existing community structures. I'm especially interested in understanding the influence of cultural and social context on mental health promotion and intervention. My work has focused on mental illness stigma, collaborative psychosocial interventions with religious congregations, and lay counselor social support. Although not directly part of my research, I also spend a lot my free time learning about the history of psychiatry and research in Africa and trying to improve my Kiswahili.

My teaching experience has included TA-ing graduate statistics and data science courses as well as an undergraduate psychopathology course. I try to teach in ways that emphasize flexible core paradigms that encourage students connect their current knowledge and empowers them to learn independently. I view academia as connected to wider communities and histories. I therefore try to use widely available technologies and engage students in critical thinking about the social, cultural, and historical context of scientific knowledge.

I grew up in Tanzania and Kenya and got my bachelor’s degree in psychology from Macalester College in Saint Paul, Minnesota. After graduating, I worked with Massachusetts General Hospital for two and a half years as an on-site project coordinator for a longitudinal microenterprise, water security, health, and social network study in Mbarara, Uganda.

## Publications
